# Generated by Django 4.1.5 on 2023-01-26 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_processing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="process",
            name="transaction_date",
            field=models.DateField(),
        ),
    ]
