# Generated by Django 4.1.5 on 2023-01-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_processing", "0002_alter_process_transaction_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="process",
            name="transaction_hour",
            field=models.TimeField(),
        ),
    ]
