# Generated by Django 4.1.5 on 2023-01-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_processing", "0005_alter_process_transaction_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="process",
            name="transaction_type",
            field=models.IntegerField(),
        ),
    ]
